"""LLM-driven "so what" for macro news pings.

Replaces the keyword heuristic in `interpret_headline()` with a real
1-sentence trader implication generated by Claude. The heuristic was
producing canned output ("Vol up; defensive rotation, T-bills wobble")
that read as fake reasoning rather than actual judgment.

Design:
  - Hard-fail clean: if ANTHROPIC_API_KEY is unset or any call fails,
    return "" so the ping just shows headline + source. We do NOT fall
    back to the heuristic — fake reasoning is worse than no reasoning.
  - Per-process LRU cache so the same headline doesn't re-bill on a
    re-run within a single cron invocation.
  - Default model is `claude-opus-4-7` (per the claude-api skill's
    "always use Opus unless user names another" rule). Override via
    NEWS_INTERPRET_MODEL env var to swap to Sonnet/Haiku for cost.

Cost at current cap (3 pings/run × edge dedup): ~30 unique calls/day
× ~700 input + ~80 output tokens at Opus 4.7 pricing ≈ $0.50/month.
Trivial. If volume grows, swap to `claude-sonnet-4-6` via env var.
"""
from __future__ import annotations

import logging
import os
from functools import lru_cache

log = logging.getLogger(__name__)

# Per the claude-api skill: use Opus 4.7 unless user explicitly names a
# different model. The model string is canonical — do not append date
# suffixes. Override via env var (e.g. NEWS_INTERPRET_MODEL=claude-sonnet-4-6)
# if you want to trade quality for cost.
LLM_MODEL = os.environ.get("NEWS_INTERPRET_MODEL", "claude-opus-4-7")

# 1-2 sentence interpretation fits comfortably under 120 tokens.
LLM_MAX_TOKENS = 120

SYSTEM_PROMPT = (
    "You are a senior macro/market strategist writing one-line trade implications "
    "for a sophisticated swing trader who runs a multi-day equity book (US large/mid-cap "
    "+ a few SGX names). The trader uses Telegram pings to stay on top of the tape "
    "between checks.\n\n"
    "Given a news headline + brief summary, write ONE sentence (max 200 chars) stating "
    "the trade implication: which sectors/assets move, in which direction, and why. "
    "Be concrete and specific. Use trader shorthand (USD strength, semis pressure, "
    "duration bid, energy bid, defensives bid). Skip greetings, boilerplate, hedging "
    "language, disclaimers, and anything that just restates the headline.\n\n"
    "If the headline is genuinely uninterpretable (a single company's product launch "
    "with no macro spillover, sports news, etc.), respond with exactly: NO_TAKE\n\n"
    "Examples:\n"
    "Headline: Iran seizes oil tanker in Strait of Hormuz\n"
    "Output: Crude bid +1-3%; energy/defense names rally; broad equities risk-off as supply premium rebuilds.\n\n"
    "Headline: Powell: Fed minutes show three members favored larger cut\n"
    "Output: Dovish surprise — duration + tech bid, USD weak, gold firm; rate-cut bets steepen for September meeting.\n\n"
    "Headline: CPI prints 0.4% MoM, hotter than 0.3% expected\n"
    "Output: Hawkish read — equities offered, USD bid, growth/long-duration pressured; rate-cut path delayed.\n\n"
    "Headline: Apple unveils new iPhone color\n"
    "Output: NO_TAKE"
)


def _try_llm_call(headline: str, summary: str) -> str | None:
    """Single API call. Returns the model's line, or None on any error."""
    try:
        # Lazy import — keeps the SDK off the hot path on cron runs that
        # don't enrich anything.
        from anthropic import Anthropic
    except ImportError:
        log.debug("anthropic SDK not installed")
        return None

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        log.debug("ANTHROPIC_API_KEY not set — skipping LLM enrichment")
        return None

    try:
        client = Anthropic(api_key=api_key)
        msg = client.messages.create(
            model=LLM_MODEL,
            max_tokens=LLM_MAX_TOKENS,
            system=SYSTEM_PROMPT,
            messages=[{
                "role": "user",
                "content": f"Headline: {headline}\nSummary: {summary[:300]}\n\nOutput:",
            }],
        )
        # Anthropic returns content as a list of blocks. Narrow by .type
        # before reading .text — TextBlock is the variant we want.
        for block in msg.content:
            if block.type == "text":
                text = block.text.strip()
                if text == "NO_TAKE":
                    return ""  # Explicit "no interpretation" — empty string
                # Strip any leading "Output:" if the model included it.
                if text.lower().startswith("output:"):
                    text = text[len("output:"):].strip()
                # Hard cap for Telegram readability — long interpretations
                # blow past the 200-char target despite the system prompt.
                return text[:240]
        return None
    except Exception as e:
        log.warning("News-interpret LLM call failed: %s", e)
        return None


@lru_cache(maxsize=512)
def _cached_interpret(headline: str, summary: str) -> str:
    """Per-process cache wrapper. Empty string is a valid cached result.

    No heuristic fallback: if the LLM call fails or no key is set, we
    return "" and let the ping omit the 💡 line entirely. Fake reasoning
    from the keyword heuristic was the original bug — empty is better.
    """
    out = _try_llm_call(headline, summary)
    return out if out is not None else ""


def interpret_with_llm(headline: str, summary: str = "") -> str:
    """Public entry — returns a 1-line "so what" string.

    Always returns a string (possibly empty). The caller treats `""` as
    "no interpretation" and skips the 💡 line in the Telegram ping.
    """
    if not headline.strip():
        return ""
    return _cached_interpret(headline.strip(), summary.strip())


def enrich_news_items(items: list[dict]) -> list[dict]:
    """Replace each item's `so_what` with an LLM-driven version.

    Mutates in-place and returns the list (for chaining). Items where
    the LLM returns empty get `so_what = ""` — the keyword-heuristic
    output is overwritten on purpose, since "fake reasoning" was the
    original complaint.
    """
    for it in items:
        headline = it.get("headline", "")
        summary = it.get("summary", "")
        if not headline:
            it["so_what"] = ""
            continue
        it["so_what"] = interpret_with_llm(headline, summary)
    return items
